apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apigw-events-pvc
  namespace: apim-k8s-uat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: apigw-events-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: [ "/bin/sleep", "3650d" ]
          resources: { }
          volumeMounts:
            - mountPath: "/opt/Axway/apigateway/events"
              name: events
      volumes:
        - name: events
          persistentVolumeClaim:
            claimName: apigw-events-pvc
