---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: anm
  namespace: apim-k8s-uat
spec:
  virtualhost:
    fqdn: anm-uatk8apim.bcthk.info
    tls:
      secretName: cert-delegation/tls-secret
  routes:
    - conditions:
        - prefix: /
      services:
        - name: anm
          port: 8090
          protocol: tls
